name: Create Issue Automatically

on:
  push:
    branches:
      - 'main'
      - 'feature/*'

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new GitHub issue
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

          curl -X POST -H "Authorization: token ${{ secrets.VYAWYWJ7AMXFQ5TOKEN }}" \
          -d '{"title":"Tarefa de implementação - '$(echo $BRANCH_NAME | sed 's/\// /g')'"}' \
          "https://api.github.com/repos/gilberto-domingos/Csharp/issues"
