name: Create Issue Automatically

on:
  push:
    branches:
      - 'main'
      - 'feature/*' 
      
jobs:
  create-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create a new GitHub issue
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

          curl -X POST -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
          -d '{"title":"Tarefa de implementação - '$(echo $BRANCH_NAME | sed 's/\// /g')'"}' \
          "https://api.github.com/repos/${{ github.repository }}/issues"
