name: Issue Automatically

on:
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'replay/*'

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Create a new GitHub issue
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          TITLE="Tarefa de implementação - $(echo $BRANCH_NAME | sed 's/\// /g')"

          curl -X POST -H "Authorization: token $MY_GITHUB_TOKEN" \
               -d "{\"title\":\"$TITLE\"}" \
               "https://api.github.com/repos/gilberto-domingos/Csharp/issues"  
